package modelo;
// Generated 08-01-2014 03:42:54 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Actividaddet generated by hbm2java
 */
@Entity
@Table(name="actividaddet"
    ,catalog="cnae"
)
public class Actividaddet  implements java.io.Serializable {


     private Integer idactividaddet;
     private Actividad actividad;
     private String actividaddet;
     private Set notases = new HashSet(0);
     private Set estructuraevaluacions = new HashSet(0);
     private Set calendarios = new HashSet(0);

    public Actividaddet() {
    }

	
    public Actividaddet(Actividad actividad, String actividaddet) {
        this.actividad = actividad;
        this.actividaddet = actividaddet;
    }
    public Actividaddet(Actividad actividad, String actividaddet, Set notases, Set estructuraevaluacions, Set calendarios) {
       this.actividad = actividad;
       this.actividaddet = actividaddet;
       this.notases = notases;
       this.estructuraevaluacions = estructuraevaluacions;
       this.calendarios = calendarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idactividaddet", unique=true, nullable=false)
    public Integer getIdactividaddet() {
        return this.idactividaddet;
    }
    
    public void setIdactividaddet(Integer idactividaddet) {
        this.idactividaddet = idactividaddet;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idactividad", nullable=false)
    public Actividad getActividad() {
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }

    
    @Column(name="actividaddet", nullable=false, length=45)
    public String getActividaddet() {
        return this.actividaddet;
    }
    
    public void setActividaddet(String actividaddet) {
        this.actividaddet = actividaddet;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="actividaddet")
    public Set getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set notases) {
        this.notases = notases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="actividaddet")
    public Set getEstructuraevaluacions() {
        return this.estructuraevaluacions;
    }
    
    public void setEstructuraevaluacions(Set estructuraevaluacions) {
        this.estructuraevaluacions = estructuraevaluacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="actividaddet")
    public Set getCalendarios() {
        return this.calendarios;
    }
    
    public void setCalendarios(Set calendarios) {
        this.calendarios = calendarios;
    }




}


