package modelo;
// Generated 08-01-2014 03:42:54 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Actividad generated by hbm2java
 */
@Entity
@Table(name="actividad"
    ,catalog="cnae"
)
public class Actividad  implements java.io.Serializable {


     private Integer idactividad;
     private String actividad;
     private Set actividaddets = new HashSet(0);
     private Set estructuraevaluacions = new HashSet(0);

    public Actividad() {
    }

	
    public Actividad(String actividad) {
        this.actividad = actividad;
    }
    public Actividad(String actividad, Set actividaddets, Set estructuraevaluacions) {
       this.actividad = actividad;
       this.actividaddets = actividaddets;
       this.estructuraevaluacions = estructuraevaluacions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idactividad", unique=true, nullable=false)
    public Integer getIdactividad() {
        return this.idactividad;
    }
    
    public void setIdactividad(Integer idactividad) {
        this.idactividad = idactividad;
    }

    
    @Column(name="actividad", nullable=false, length=45)
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="actividad")
    public Set getActividaddets() {
        return this.actividaddets;
    }
    
    public void setActividaddets(Set actividaddets) {
        this.actividaddets = actividaddets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="actividad")
    public Set getEstructuraevaluacions() {
        return this.estructuraevaluacions;
    }
    
    public void setEstructuraevaluacions(Set estructuraevaluacions) {
        this.estructuraevaluacions = estructuraevaluacions;
    }




}


