package modelo;
// Generated 08-01-2014 03:42:54 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Asistencia generated by hbm2java
 */
@Entity
@Table(name="asistencia"
    ,catalog="cnae"
)
public class Asistencia  implements java.io.Serializable {


     private int idasistencia;
     private Asignatura asignatura;
     private Calendario calendario;
     private Estudiantes estudiantes;
     private String asistencia;

    public Asistencia() {
    }

    public Asistencia(int idasistencia, Asignatura asignatura, Calendario calendario, Estudiantes estudiantes, String asistencia) {
       this.idasistencia = idasistencia;
       this.asignatura = asignatura;
       this.calendario = calendario;
       this.estudiantes = estudiantes;
       this.asistencia = asistencia;
    }
   
     @Id 

    
    @Column(name="idasistencia", unique=true, nullable=false)
    public int getIdasistencia() {
        return this.idasistencia;
    }
    
    public void setIdasistencia(int idasistencia) {
        this.idasistencia = idasistencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idasignatura", nullable=false)
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcalendario", nullable=false)
    public Calendario getCalendario() {
        return this.calendario;
    }
    
    public void setCalendario(Calendario calendario) {
        this.calendario = calendario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idestudiante", nullable=false)
    public Estudiantes getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Estudiantes estudiantes) {
        this.estudiantes = estudiantes;
    }

    
    @Column(name="asistencia", nullable=false, length=2)
    public String getAsistencia() {
        return this.asistencia;
    }
    
    public void setAsistencia(String asistencia) {
        this.asistencia = asistencia;
    }




}


