package modelo;
// Generated 08-01-2014 03:42:54 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calendario generated by hbm2java
 */
@Entity
@Table(name="calendario"
    ,catalog="cnae"
)
public class Calendario  implements java.io.Serializable {


     private Integer idcalendario;
     private Asignatura asignatura;
     private Actividaddet actividaddet;
     private Date fecha;
     private Set notases = new HashSet(0);
     private Set asistencias = new HashSet(0);

    public Calendario() {
    }

	
    public Calendario(Asignatura asignatura, Actividaddet actividaddet, Date fecha) {
        this.asignatura = asignatura;
        this.actividaddet = actividaddet;
        this.fecha = fecha;
    }
    public Calendario(Asignatura asignatura, Actividaddet actividaddet, Date fecha, Set notases, Set asistencias) {
       this.asignatura = asignatura;
       this.actividaddet = actividaddet;
       this.fecha = fecha;
       this.notases = notases;
       this.asistencias = asistencias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcalendario", unique=true, nullable=false)
    public Integer getIdcalendario() {
        return this.idcalendario;
    }
    
    public void setIdcalendario(Integer idcalendario) {
        this.idcalendario = idcalendario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idasignatura", nullable=false)
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idactividaddet", nullable=false)
    public Actividaddet getActividaddet() {
        return this.actividaddet;
    }
    
    public void setActividaddet(Actividaddet actividaddet) {
        this.actividaddet = actividaddet;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="calendario")
    public Set getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set notases) {
        this.notases = notases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="calendario")
    public Set getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set asistencias) {
        this.asistencias = asistencias;
    }




}


