package modelo;
// Generated 08-01-2014 03:42:54 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name="docente"
    ,catalog="cnae"
)
public class Docente  implements java.io.Serializable {


     private Integer iddocente;
     private String nombre;
     private String apellido;
     private String usuario;
     private String contrasena;

    public Docente() {
    }

    public Docente(String nombre, String apellido, String usuario, String contrasena) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.usuario = usuario;
       this.contrasena = contrasena;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddocente", unique=true, nullable=false)
    public Integer getIddocente() {
        return this.iddocente;
    }
    
    public void setIddocente(Integer iddocente) {
        this.iddocente = iddocente;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="usuario", nullable=false, length=45)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="contrasena", nullable=false, length=45)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }




}


