package modelo;
// Generated 08-01-2014 03:42:54 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Estructuraevaluacion generated by hbm2java
 */
@Entity
@Table(name="estructuraevaluacion"
    ,catalog="cnae"
)
public class Estructuraevaluacion  implements java.io.Serializable {


     private Integer idestructuraevaluacion;
     private Asignatura asignatura;
     private Actividaddet actividaddet;
     private Actividad actividad;
     private Double valor;

    public Estructuraevaluacion() {
    }

	
    public Estructuraevaluacion(Asignatura asignatura, Actividaddet actividaddet, Actividad actividad) {
        this.asignatura = asignatura;
        this.actividaddet = actividaddet;
        this.actividad = actividad;
    }
    public Estructuraevaluacion(Asignatura asignatura, Actividaddet actividaddet, Actividad actividad, Double valor) {
       this.asignatura = asignatura;
       this.actividaddet = actividaddet;
       this.actividad = actividad;
       this.valor = valor;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idestructuraevaluacion", unique=true, nullable=false)
    public Integer getIdestructuraevaluacion() {
        return this.idestructuraevaluacion;
    }
    
    public void setIdestructuraevaluacion(Integer idestructuraevaluacion) {
        this.idestructuraevaluacion = idestructuraevaluacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idasignatura", nullable=false)
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idactividaddet", nullable=false)
    public Actividaddet getActividaddet() {
        return this.actividaddet;
    }
    
    public void setActividaddet(Actividaddet actividaddet) {
        this.actividaddet = actividaddet;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idactividad", nullable=false)
    public Actividad getActividad() {
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }

    
    @Column(name="valor", precision=22, scale=0)
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }




}


