package modelo;
// Generated 08-01-2014 03:42:54 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estudiantes generated by hbm2java
 */
@Entity
@Table(name="estudiantes"
    ,catalog="cnae"
)
public class Estudiantes  implements java.io.Serializable {


     private Integer idestudiante;
     private Asignatura asignatura;
     private String nombreE;
     private String apellidoE;
     private String carnet;
     private Integer celular;
     private String email;
     private Set asistencias = new HashSet(0);
     private Set notases = new HashSet(0);

    public Estudiantes() {
    }

	
    public Estudiantes(Asignatura asignatura, String nombreE, String apellidoE) {
        this.asignatura = asignatura;
        this.nombreE = nombreE;
        this.apellidoE = apellidoE;
    }
    public Estudiantes(Asignatura asignatura, String nombreE, String apellidoE, String carnet, Integer celular, Set asistencias, Set notases) {
       this.asignatura = asignatura;
       this.nombreE = nombreE;
       this.apellidoE = apellidoE;
       this.carnet = carnet;
       this.celular = celular;
       this.asistencias = asistencias;
       this.notases = notases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idestudiante", unique=true, nullable=false)
    public Integer getIdestudiante() {
        return this.idestudiante;
    }
    
    public void setIdestudiante(Integer idestudiante) {
        this.idestudiante = idestudiante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idasignatura", nullable=false)
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

    
    @Column(name="nombreE", nullable=false, length=45)
    public String getNombreE() {
        return this.nombreE;
    }
    
    public void setNombreE(String nombreE) {
        this.nombreE = nombreE;
    }

    
    @Column(name="apellidoE", nullable=false, length=45)
    public String getApellidoE() {
        return this.apellidoE;
    }
    
    public void setApellidoE(String apellidoE) {
        this.apellidoE = apellidoE;
    }

    
    @Column(name="carnet", length=10)
    public String getCarnet() {
        return this.carnet;
    }
    
    public void setCarnet(String carnet) {
        this.carnet = carnet;
    }

    
    @Column(name="celular")
    public Integer getCelular() {
        return this.celular;
    }
    
    public void setCelular(Integer celular) {
        this.celular = celular;
    }
    
    @Column(name="email")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estudiantes")
    public Set getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set asistencias) {
        this.asistencias = asistencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estudiantes")
    public Set getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set notases) {
        this.notases = notases;
    }




}


