package modelo;
// Generated 08-01-2014 03:42:54 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Notas generated by hbm2java
 */
@Entity
@Table(name="notas"
    ,catalog="cnae"
)
public class Notas  implements java.io.Serializable {


     private int idnotas;
     private Asignatura asignatura;
     private Calendario calendario;
     private Estudiantes estudiantes;
     private Actividaddet actividaddet;
     private double nota;

    public Notas() {
    }

    public Notas(int idnotas, Asignatura asignatura, Calendario calendario, Estudiantes estudiantes, Actividaddet actividaddet, double nota) {
       this.idnotas = idnotas;
       this.asignatura = asignatura;
       this.calendario = calendario;
       this.estudiantes = estudiantes;
       this.actividaddet = actividaddet;
       this.nota = nota;
    }
   
     @Id 

    
    @Column(name="idnotas", unique=true, nullable=false)
    public int getIdnotas() {
        return this.idnotas;
    }
    
    public void setIdnotas(int idnotas) {
        this.idnotas = idnotas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idasignatura", nullable=false)
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcalendario", nullable=false)
    public Calendario getCalendario() {
        return this.calendario;
    }
    
    public void setCalendario(Calendario calendario) {
        this.calendario = calendario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idestudiante", nullable=false)
    public Estudiantes getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Estudiantes estudiantes) {
        this.estudiantes = estudiantes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idactividaddet", nullable=false)
    public Actividaddet getActividaddet() {
        return this.actividaddet;
    }
    
    public void setActividaddet(Actividaddet actividaddet) {
        this.actividaddet = actividaddet;
    }

    
    @Column(name="nota", nullable=false, precision=22, scale=0)
    public double getNota() {
        return this.nota;
    }
    
    public void setNota(double nota) {
        this.nota = nota;
    }




}


