package modelo;
// Generated 08-01-2014 03:42:54 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Universidad generated by hbm2java
 */
@Entity
@Table(name="universidad"
    ,catalog="cnae"
)
public class Universidad  implements java.io.Serializable {


     private Integer iduniversidad;
     private String nombreU;
     private String siglas;
     private byte[] logo;
     private Set facultads = new HashSet(0);

    public Universidad() {
    }

	
    public Universidad(String nombreU) {
        this.nombreU = nombreU;
    }
    public Universidad(String nombreU, String siglas, byte[] logo, Set facultads) {
       this.nombreU = nombreU;
       this.siglas = siglas;
       this.logo = logo;
       this.facultads = facultads;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iduniversidad", unique=true, nullable=false)
    public Integer getIduniversidad() {
        return this.iduniversidad;
    }
    
    public void setIduniversidad(Integer iduniversidad) {
        this.iduniversidad = iduniversidad;
    }

    
    @Column(name="nombreU", nullable=false, length=45)
    public String getNombreU() {
        return this.nombreU;
    }
    
    public void setNombreU(String nombreU) {
        this.nombreU = nombreU;
    }

    
    @Column(name="siglas", length=45)
    public String getSiglas() {
        return this.siglas;
    }
    
    public void setSiglas(String siglas) {
        this.siglas = siglas;
    }

    
    @Column(name="logo")
    public byte[] getLogo() {
        return this.logo;
    }
    
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="universidad")
    public Set getFacultads() {
        return this.facultads;
    }
    
    public void setFacultads(Set facultads) {
        this.facultads = facultads;
    }




}


